### ISSUE TITLE
Where to buy the Black Power supply block ?

### ISSUE THREAD

**Issue by ezYakaEagle442** [Sheldonwl/rpi-travel-case#1]
Hi @Sheldonwl ,
First of all, thank you for sharing your experience, I would like as well to play with K3S on RPI, I have prepared my shopping list and have found all the components except the Black Power supply block on the left of the photo, could you please enlight me providing a link to an e-commerce site , or even better the manufacturer name & product reference please ?

Thanks in advance,
Steve
![power-supply-unit-bloc](https://user-images.githubusercontent.com/43554247/87314080-095f7700-c523-11ea-9350-f4632eb8f0a4.jpg)

**Comment by Sheldonwl** [comment]
Hi @ezYakaEagle442, 

It's the Anker Power Port 10. It has enough juice to power the Pi's, however not if all of them will run on full power. Meaning, all peripherals in use and running on max load. For that I would recommend a better power supply. 
Here's the official website: https://www.anker.com/products/variant/powerport-10/A2133111 
Good luck and have fun with your project! 

Kind regards, 
Sheldon
